# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\E7\private\QT\串口调试助手\serial_debug.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 571, 361))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.textBrowser_receive = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_receive.setGeometry(QtCore.QRect(10, 20, 551, 331))
        self.textBrowser_receive.setOpenLinks(True)
        self.textBrowser_receive.setObjectName("textBrowser_receive")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 0, 211, 361))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_serial_operation = QtWidgets.QLabel(self.groupBox_2)
        self.label_serial_operation.setGeometry(QtCore.QRect(10, 20, 54, 31))
        self.label_serial_operation.setObjectName("label_serial_operation")
        self.pushButton_open_close = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_open_close.setGeometry(QtCore.QRect(75, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_open_close.setFont(font)
        self.pushButton_open_close.setObjectName("pushButton_open_close")
        self.label_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_status.setGeometry(QtCore.QRect(170, 25, 20, 20))
        self.label_status.setStyleSheet("#label_status{\n"
"    border-radius: 10px;\n"
"    background-color:gray ;\n"
"}\n"
"#label_status[isOn=\"true\"]{\n"
"background-color: green;\n"
"}")
        self.label_status.setText("")
        self.label_status.setProperty("isOn", False)
        self.label_status.setObjectName("label_status")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 70, 191, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(16)
        self.formLayout.setObjectName("formLayout")
        self.label_serial_select = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial_select.setObjectName("label_serial_select")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial_select)
        self.comboBox_port = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_port.setFont(font)
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_serial_baud = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial_baud.setObjectName("label_serial_baud")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_serial_baud)
        self.comboBox_baud = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_baud.setFont(font)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.label_serial_stop = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial_stop.setObjectName("label_serial_stop")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_serial_stop)
        self.comboBox_stop = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_stop.setFont(font)
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_stop)
        self.label_serial_data = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial_data.setObjectName("label_serial_data")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_serial_data)
        self.comboBox_data = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_data.setFont(font)
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_data)
        self.label_serial_parity = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial_parity.setObjectName("label_serial_parity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_serial_parity)
        self.comboBox_partial = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_partial.setFont(font)
        self.comboBox_partial.setObjectName("comboBox_partial")
        self.comboBox_partial.addItem("")
        self.comboBox_partial.addItem("")
        self.comboBox_partial.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_partial)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 290, 191, 58))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_save = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_save)
        self.pushButton_clean_rcv = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clean_rcv.setFont(font)
        self.pushButton_clean_rcv.setObjectName("pushButton_clean_rcv")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_clean_rcv)
        self.checkBox_display = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_display.setFont(font)
        self.checkBox_display.setObjectName("checkBox_display")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_display)
        self.checkBox_timestamp = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_timestamp.setFont(font)
        self.checkBox_timestamp.setObjectName("checkBox_timestamp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_timestamp)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 360, 571, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.plainTextEdit_send = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_send.setGeometry(QtCore.QRect(10, 20, 551, 91))
        self.plainTextEdit_send.setObjectName("plainTextEdit_send")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 360, 211, 111))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(7, 20, 191, 91))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.pushButton_send = QtWidgets.QPushButton(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setObjectName("pushButton_send")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_send)
        self.checkBox_send_peroidically = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.checkBox_send_peroidically.setFont(font)
        self.checkBox_send_peroidically.setObjectName("checkBox_send_peroidically")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_send_peroidically)
        self.lineEdit_timer_value = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_timer_value.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_timer_value.setFont(font)
        self.lineEdit_timer_value.setObjectName("lineEdit_timer_value")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_timer_value)
        self.pushButton_clean_send = QtWidgets.QPushButton(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_clean_send.setFont(font)
        self.pushButton_clean_send.setObjectName("pushButton_clean_send")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_clean_send)
        self.checkBox_hex_send = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.checkBox_hex_send.setFont(font)
        self.checkBox_hex_send.setObjectName("checkBox_hex_send")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_hex_send)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 480, 761, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout.addWidget(self.lineEdit_filename)
        self.pushButton_openfile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_openfile.sizePolicy().hasHeightForWidth())
        self.pushButton_openfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_openfile.setFont(font)
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.horizontalLayout.addWidget(self.pushButton_openfile)
        self.pushButton_sendfile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_sendfile.setFont(font)
        self.pushButton_sendfile.setObjectName("pushButton_sendfile")
        self.horizontalLayout.addWidget(self.pushButton_sendfile)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_baud.setCurrentIndex(1)
        self.comboBox_stop.setCurrentIndex(0)
        self.comboBox_data.setCurrentIndex(3)
        self.comboBox_partial.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试助手V1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "串口接收区"))
        self.label_serial_operation.setText(_translate("MainWindow", "串口操作"))
        self.pushButton_open_close.setText(_translate("MainWindow", "打开串口"))
        self.label_serial_select.setText(_translate("MainWindow", "串口选择"))
        self.label_serial_baud.setText(_translate("MainWindow", "波特率"))
        self.comboBox_baud.setCurrentText(_translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "12400"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "38400"))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "57600"))
        self.comboBox_baud.setItemText(6, _translate("MainWindow", "115200"))
        self.label_serial_stop.setText(_translate("MainWindow", "停止位"))
        self.comboBox_stop.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stop.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stop.setItemText(2, _translate("MainWindow", "2"))
        self.label_serial_data.setText(_translate("MainWindow", "数据位"))
        self.comboBox_data.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_data.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_data.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_data.setItemText(3, _translate("MainWindow", "8"))
        self.label_serial_parity.setText(_translate("MainWindow", "校验位"))
        self.comboBox_partial.setItemText(0, _translate("MainWindow", "No"))
        self.comboBox_partial.setItemText(1, _translate("MainWindow", "Odd"))
        self.comboBox_partial.setItemText(2, _translate("MainWindow", "Even"))
        self.pushButton_save.setText(_translate("MainWindow", "保存窗口"))
        self.pushButton_clean_rcv.setText(_translate("MainWindow", "清除接收"))
        self.checkBox_display.setText(_translate("MainWindow", "16进制显示"))
        self.checkBox_timestamp.setText(_translate("MainWindow", "时间戳"))
        self.groupBox_3.setTitle(_translate("MainWindow", "串口发送区"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
        self.checkBox_send_peroidically.setText(_translate("MainWindow", "定时发送/ms"))
        self.lineEdit_timer_value.setText(_translate("MainWindow", "100"))
        self.pushButton_clean_send.setText(_translate("MainWindow", "清除发送"))
        self.checkBox_hex_send.setText(_translate("MainWindow", "16进制发送"))
        self.pushButton_openfile.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_sendfile.setText(_translate("MainWindow", "发送文件"))

